export const FETCH_REPOS_START = 'FETCH_REPOS_START';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_ERROR = 'FETCH_REPOS_ERROR';
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
